spring:
  application:
    name: cloud-consumerconsul-order80
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order80