spring:
  application:
    name: cloud-provider-payment8001
server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示IP地址
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
      #lease-renewal-interval-in-seconds: 1
    #Eurekaf服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
