server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: hystrix-payment8001